### ISSUE TITLE
Not compatible with e10s

### ISSUE THREAD

**Issue by rugk** [seleznev/firefox-extension-simple-bookmarks-menu#10]
Is this add-on compatible with Electrolysis (e10s)? Electrolysis is the new architecture of Firefox and Mozilla already rolls out some stable Firefox versions with e10s enabled.

More information:
* https://arewee10syet.com/
* https://wiki.mozilla.org/Electrolysis

----

According to [ACR](https://addons.mozilla.org/firefox/addon/add-on-compatibility-reporter/) this add-on is not compatible with e10s. You can change the manifest file of your add-on to mark it as compatible with e10s.

**Comment by paulri** [comment]
I have been using Simple bookmarks menu for months now, on FF beta and FDE, with e10s enabled, and this addon has been working smoothly without a hiccup.

**Comment by rugk** [comment]
Nice, if it works indeed the author just has to mark it as compatible.

**Comment by seleznev** [comment]
I uploaded new version (0.9.1) to AMO, so it should be fixed soon.

Many thanks for notice! :)
