### ISSUE TITLE
Firefox 57

### ISSUE THREAD

**Issue by MedicOP** [seleznev/firefox-extension-simple-bookmarks-menu#15]
Hi

The extension does not work with the latest version of Firefox

**Comment by seleznev** [comment]
Hello!

This extension uses "legacy API" that Mozilla dropped in Firefox 57. So it should be rewritten from scratch with WebExtension API.

However, I have no time to do it, so I mark this extension as deprecated. If you will find any good alternatives. please let me know and I will add link on AMO page to help users find them.

So sorry about it. :(
