### ISSUE TITLE
Pale Moon Compatibility

### ISSUE THREAD

**Issue by JeremyWW** [seleznev/firefox-extension-simple-bookmarks-menu#6]
Hi,

I've hacked minVersion in install.rtf to allow installation in Pale Moon which needs v24+ compatibility, but wondered if you could make the change permanent to allow proper installation / updating in the future.

Thanks

**Comment by seleznev** [comment]
I never used it but I don't see Australis interface on screenshots. This extension only for Australis. I'm sorry, but I will not support Pale Moon if it doesn't use new interface.

**Comment by JeremyWW** [comment]
That's OK - I'm using Waterfox now anyway and Simple Bookmarks works fine.
