### ISSUE TITLE
Options "Bookmark this page" and "Open in tabs" remain visible, regardless of settings

### ISSUE THREAD

**Issue by userneu** [seleznev/firefox-extension-simple-bookmarks-menu#8]
Firefox 43.0a2
Simple bookmarks menu 0.8

**Comment by seleznev** [comment]
What operating systems (and version) do you use?

**Comment by userneu** [comment]
Win7 Pro x64

**Comment by userneu** [comment]
Hello.
Any news?

**Comment by userneu** [comment]
woops
Iam sorry. Really
Your extension works well. In my case I use "Classic Bookmark Button" extension to open bookmark menu
Sorry again
